OrcaBus/platform-cdk-constructs

- packages/docs/@orcabus/namespaces/ecs/README.md
- packages/docs/@orcabus/namespaces/ecs/classes/EcsTaskConstruct.md
- packages/docs/@orcabus/namespaces/ecs/interfaces/FargateEcsTaskConstructProps.md
- packages/docs/@orcabus/namespaces/ecs/type-aliases/Architecture.md
- packages/docs/@orcabus/namespaces/ecs/variables/CPU_ARCHITECTURE_MAP.md
- packages/docs/@orcabus/namespaces/ecs/variables/LAMBDA_ARCHITECTURE_MAP.md
- packages/docs/README.md
- packages/ecs/config.ts
- packages/ecs/index.ts
- packages/index.ts
Repetitive construct used for fargate ECS tasks in our Orcabus repository
> Added ECS Constructs

- packages/lambda/index.ts
> Lambda layer should be global on a 'per-stack' level

- packages/lambda/index.ts
Initialise maps before using 'has' attribute on scope construct
> Need to initialise maps first before querying map attributes

- packages/deployment-stack-pipeline/pipeline.ts
Closes #16 
* Adds the source repository to the github tags
> feat: add github source to tags

- packages/lambda/index.ts
- packages/utils/index.ts
See discussion in https://github.com/aws/aws-cdk/issues/1754#issuecomment-513542145
> Update resolveStageName to use Stack.of(this) for context

- .github/workflows/pr-tests.yml
- package.json
- packages/jest.config.js
- packages/package.json
- packages/test/providerFunction.test.ts
- pnpm-lock.yaml
* Adds the missing unit test for the `ProviderFunction`.
* Add test CI step.
> test: add provider function unit test

- packages/utils/index.ts
Added icav2 project ids and pipeline cache buckets + prefixes per stagename
> Added pipeline cache prefixes and default icav2 project ids per stage name

- packages/utils/index.ts
Some dodgy but effective work, solution discussion here #46
> Stack is under 'scope.node.scope' so we can check if the stageName property is there

- packages/deployment-stack-pipeline/pipeline.ts
- packages/docs/@orcabus/namespaces/deploymentPipeline/classes/DeploymentStackPipeline.md
- packages/docs/@orcabus/namespaces/deploymentPipeline/interfaces/DeploymentStackPipelineProps.md
- allow inclusion and exclusion filter props
> Feat(codepipeline): Update pipeline props

- packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/metadata/__init__.py
- packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/metadata/sample_helpers.py
> Fix metadata helpers

- packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/workflow/__init__.py
- packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/workflow/payload_helpers.py
- packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/workflow/workflow_run_helpers.py
Use state orcabus Id to select current state object to then get payload id
> Update state / payload helper functions

- packages/api-gateway/config.ts
As discussed, add "http://localhost:3000" to dev api cors.
> add local host in dev api cors

- packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/fastq_decompression/models.py
- packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/fastq_decompression/query_helpers.py
Fastq decompression service can query on fastq id list as well as fastq set id list
> Allow query of fastq id for decompression jobs

- packages/docs/@orcabus/namespaces/ecs/classes/EcsFargateTaskConstruct.md
- packages/ecs/index.ts
Need to run a cdk nag suppression on the task execution role, so we need to expose it in the construct
> Add task execution-role fargate construct

- packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/fastq_decompression/update_helpers.py
Required when running succeeded status
> Add output to ora update

- packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/fastq/models.py
- packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/fastq_decompression/create_helpers.py
- packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/fastq_decompression/models.py
- packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/filemanager/models.py
Various updates to use type dict models and typing literals
> Updated fastq decompression create job

- packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/fastq_decompression/__init__.py
- packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/fastq_decompression/create_helpers.py
- packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/fastq_decompression/models.py
- packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/fastq_decompression/query_helpers.py
- packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/fastq_decompression/update_helpers.py
- packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/fastq_unarchiving/__init__.py
- packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/fastq_unarchiving/update_helpers.py
- packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/utils/requests_helpers.py
And move to TypeDict dictionaries for type hinting in kwargs for patch / post requests
> Use json over params for patch and post requests

- packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/fastq/__init__.py
- packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/fastq/globals.py
- packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/fastq/query_helpers.py
- packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/fastq/update_helpers.py
With the new rgid endpoint we can now retrieve fastq objects by their rgid
> Added the get by rgid command

- packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/sequence/__init__.py
- packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/sequence/globals.py
- packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/sequence/models.py
- packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/sequence/sequence_helpers.py
Added functions to use instrument run id endpoints to collect libraries and samplesheets
> Update sequence run helpers to new endpoints

- packages/lambda/layers/icav2_tools/poetry.lock
- packages/lambda/layers/icav2_tools/pyproject.toml
Also update lock file, otherwise, cdk refuses to build the package
> Add primary and secondary sources to toml

- packages/lambda/layers/icav2_tools/pyproject.toml
Also commented out the testpypi since we're no longer using a dev release of wrapica
> Update to latest release of the wrapica package

- packages/docs/@orcabus/namespaces/sharedConfig/namespaces/fileManager/variables/FILE_MANAGER_ACCESS_KEY_ARNS.md
- packages/docs/@orcabus/namespaces/sharedConfig/namespaces/fileManager/variables/FILE_MANAGER_CACHE_BUCKETS.md
- packages/docs/@orcabus/namespaces/sharedConfig/namespaces/fileManager/variables/FILE_MANAGER_DOMAIN_PREFIX.md
- packages/docs/@orcabus/namespaces/sharedConfig/namespaces/fileManager/variables/FILE_MANAGER_INGEST_ROLE.md
- packages/docs/@orcabus/namespaces/sharedConfig/namespaces/fileManager/variables/FILE_MANAGER_PRESIGN_USER.md
- packages/docs/@orcabus/namespaces/sharedConfig/namespaces/fileManager/variables/FILE_MANAGER_PRESIGN_USER_SECRET.md
- packages/shared-config/file-manager.ts
* Adds the test data bucket. Related to https://github.com/OrcaBus/service-filemanager/issues/46.
> feat: add filemanager test data bucket

- packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/workflow/models.py
- packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/workflow/workflow_run_helpers.py
API response for the worklfow manager is inconsistent with the WRSC events, instead, coerce the API response to match the WRSC event schema type.
> Workflow object should look like the new event type

- packages/lambda/layers/icav2_tools/poetry.lock
- packages/lambda/layers/icav2_tools/pyproject.toml
Update wrapica to latest dev version for research data bucket support (which doesn't use a keyPrefix)
> Wrapica updates

- packages/docs/@orcabus/namespaces/sharedConfig/namespaces/fileManager/variables/FILE_MANAGER_ACCESS_KEY_ARNS.md
- packages/docs/@orcabus/namespaces/sharedConfig/namespaces/fileManager/variables/FILE_MANAGER_CACHE_BUCKETS.md
- packages/docs/@orcabus/namespaces/sharedConfig/namespaces/fileManager/variables/FILE_MANAGER_CROSS_ACCOUNT_BUCKETS.md
- packages/docs/@orcabus/namespaces/sharedConfig/namespaces/fileManager/variables/FILE_MANAGER_DOMAIN_PREFIX.md
- packages/docs/@orcabus/namespaces/sharedConfig/namespaces/fileManager/variables/FILE_MANAGER_INGEST_ROLE.md
- packages/docs/@orcabus/namespaces/sharedConfig/namespaces/fileManager/variables/FILE_MANAGER_PRESIGN_USER.md
- packages/docs/@orcabus/namespaces/sharedConfig/namespaces/fileManager/variables/FILE_MANAGER_PRESIGN_USER_SECRET.md
- packages/shared-config/file-manager.ts
Related to https://github.com/OrcaBus/service-filemanager/issues/56
> feat: add filemanager project data bucket

- packages/lambda/layers/orcabus_api_tools/src/orcabus_api_tools/filemanager/file_helpers.py
Adds consistency to other functions where we prioritise storage class and event time
> Missed a place where ingest ids are converted into objects
